[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.19.0"
  NEXT_PUBLIC_APP_URL = "https://ytsl.netlify.app"
  ENABLE_KV_STORE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[dev]
  functions = "netlify/functions"
  publish = ".next"

[edge_functions]
  force = true