# @format

services:
  - type: web
    name: ytsearchleads
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    nodeVersion: 18.x
    envVars:
      - key: NEXT_PUBLIC_APP_URL
        sync: false
    autoDeploy: true
